[package]
name = "um32"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary-int = "1.2.0"
bitmatch = "0.1.1"
byteorder = "1.5.0"
ra-ap-rustc_index = "0.118.0"
